### ISSUE TITLE
Exporting point clouds

### ISSUE THREAD

**Issue by mihaibujanca** [stetro/project-tango-poc#4]
I tried the pc app, and did not manage to export any file.
Upon debugging, I noticed that `pointCollection.getCount();` is always 0 (in pc/util/PointCloudManager.java:59) - so pointCollection is empty (but not null, since there's not NullPointerException).

I'll be looking into it a bit more soon, but it'd be great if you could give any clues as to why this might happen.

**Comment by stetro** [comment]
Hey, as you may have noticed, this repo is on heavy construction due to my master thesis implementation. I plan to refactor all those apps back as simple examples. I've done this for pc now and the pointcloud export should now work fine and its showing the resulting pointcloud path in a Toast. Greetings

**Comment by mihaibujanca** [comment]
Great, I'll try it sometime this week again probably and tell you how it goes
