### ISSUE TITLE
Libraries version

### ISSUE THREAD

**Issue by lucadambros** [stetro/project-tango-poc#8]
Hi,
I saw your work here and I want to know what version of library do you use.
After I download them, what I have to do?
Can you help me?

Thanks

**Comment by stetro** [comment]
https://github.com/stetro/project-tango-poc/issues/6#issuecomment-203961035

Hey! Libraries like PCL, OpenCV and OpenChisel need to be corsscompiled and placed according to the makefiles in these POC's. Since these are only proof of concepts which I have done during my master thesis I cannot give a detailed build description for each of them ... sorry! Because most of them are grown during test phases.
